package cli

// Objects subcommands.

import (
	"github.com/spf13/cobra"

	"petris.dev/psbox/internal/complete"
	"petris.dev/psbox/internal/config"
	"petris.dev/psbox/internal/objects"
)

func newObjectsCommand(svc *objects.Service, paths config.Paths) *cobra.Command {
	var objectPath string
	cmd := &cobra.Command{
		Use:   "objects",
		Short: "Install and list objects and desktop files",
	}
	cmd.PersistentFlags().StringVar(&objectPath, "objects", paths.ObjectPath, "path to configuration objects")

	cmd.AddCommand(&cobra.Command{
		Use:   "install",
		Short: "Install desktop launcher files from configuration",
		Args:  noArgs("install"),
		RunE: func(cmd *cobra.Command, args []string) error {
			return svc.Install(paths.WithObjectPath(objectPath))
		},
	})
	cmd.AddCommand(&cobra.Command{
		Use:   "cleanup",
		Short: "Remove desktop files marked as generated by psbox",
		Args:  noArgs("cleanup"),
		RunE: func(cmd *cobra.Command, args []string) error {
			return svc.Cleanup(paths.WithObjectPath(objectPath))
		},
	})

	var quiet bool
	list := &cobra.Command{
		Use:       "list {applications|desktop|autostart}",
		Short:     "List objects",
		Args:      listArgs,
		ValidArgs: []string{"applications", "desktop", "autostart"},
		RunE: func(cmd *cobra.Command, args []string) error {
			return svc.List(paths.WithObjectPath(objectPath), args[0], quiet, cmd.OutOrStdout())
		},
	}
	list.Flags().BoolVarP(&quiet, "quiet", "q", false, "list objects without any additional information")
	cmd.AddCommand(list)

	cmd.AddCommand(&cobra.Command{
		Use:               "render <application>",
		Short:             "Render desktop and autostart files for an application",
		Args:              renderArgs,
		ValidArgsFunction: complete.Applications,
		RunE: func(cmd *cobra.Command, args []string) error {
			return svc.Render(paths.WithObjectPath(objectPath), args[0], cmd.OutOrStdout())
		},
	})
	return cmd
}
